# Generated by Django 4.0.1 on 2023-04-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_member', models.CharField(max_length=15)),
                ('cart_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('cart_prod', models.CharField(max_length=10)),
                ('cart_qty', models.CharField(max_length=8)),
            ],
        ),
    ]
